source("Ind.Test.R")
library(tictoc)

RunAll_no_multi<-function(meta,condition,celltype,basetype,individual)
{
saveRDS(meta,"meta.RDS")
times=c()
print(1);
tic();res<-test_logistic(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="logistic";out=toc();dat["time"]=out$toc-out$tic;ret=dat;times<-c(times,out$tic-out$toc);
print(2);
tic();res<-test_direchlet(meta,condition,celltype,individual,method="common",basetype="");nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="dirich";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(3);
tic();res<-test_direchlet_base(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="dirich_alt";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(4);
#tic();res<-test_multi(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(5);
#tic();res<-test_multi_mixed_overdisp(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial_mixed_overdisp";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(6);
#tic();res<-test_multi_mixed(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial_mixed";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(7);
tic();res<-test_poisson(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Poisson";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(8);
tic();res<-test_nb(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="NB";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(9);
tic();res<-test_logistic_mixed(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="lostic_mixed";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(10);
tic();res<-test_wilcox_base(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Wilcox_base";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(11);
tic();res<-test_wilcox(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Wilcox_Percent";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(12);
tic();res<-test_chi(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Chi";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(13);
tic();res<-test_fisher(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Fisher";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(14);
tic();res<-test_propel(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="propel_asin";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
print(15)
tic();res<-test_propel(meta,condition,celltype,individual,"logit");nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="propel_logit";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
return(ret)
}
