source("Ind.Test.R")
library(tictoc)

RunAll<-function(meta,condition,celltype,basetype,individual)
{
times=c()
tic();res<-test_logistic(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="logistic";out=toc();dat["time"]=out$toc-out$tic;ret=dat;times<-c(times,out$tic-out$toc);
tic();res<-test_direchlet(meta,condition,celltype,individual,method="common",basetype="");nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="dirich";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_direchlet_base(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="dirich_alt";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_multi(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_multi_mixed_overdisp(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial_mixed_overdisp";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_multi_mixed(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="multinomial_mixed";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_poisson(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Poisson";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_logistic_mixed(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="lostic_mixed";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_wilcox_base(meta,condition,celltype,individual,basetype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Wilcox_base";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_wilcox(meta,condition,celltype,individual);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Wilcox_Percent";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_chi(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Chi";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
tic();res<-test_fisher(meta,condition,celltype);nams=names(res);pvals=as.numeric(res);dat=data.frame(nams);dat["pval"]=pvals;colnames(dat)[1]="CellType";dat["method"]="Fisher";out=toc();dat["time"]=out$toc-out$tic;ret=rbind(ret,dat);times<-c(times,out$tic-out$toc);
return(ret)
}
